[KNW-187] Implement new AnkiWeb signup/login screens (#1324)
* Implement AnkiWeb signup/login screens

* Prefill AnkiHub email

* Only update code button's label on first Email confirmation dialog

Also fixes a race issue with timer_is_active() by adding a check for
remaining_seconds

* Fix Sign up button enabled without accepting terms

Regressed in e3d3f102b8c72416e392466d1c23768a125f1ed5

* Make it clearer it's an AnkiWeb account

* Clean up timers after widget transitions

* Fix typo

* Break counter status into separate line

* Remove unused testing function

* Use keyword arguments to constructors where possible

* Fix mypy errors

* Remove extra line break

* Avoid shadowing argument

* Fix typo

* Add tests

* Avoid new union syntax

Fails on Qt5:
> TypeError: unsupported operand type(s) for |: 'sip.wrappertype' and 'sip.wrappertype'

* Fix state of Sign in button not updating after email change

* Fix mypy errors in tests

* Ensure code is valid

* Disable 'Get Code' button when timer is running

* Disable code input before code is requested

* Prevent user resize while allowing dynamic resize

* Reduce layout jumps when status text changes

* Show an inline progress indicator

* Change the mask character to a star

* Remove outdated test

* Update taskman patch in tests

* Fix form items not expanding in macOS's native theme

* Improve spacing

* Make errors bold

* Make links bold

* Make input labels bold

* Add SVG error icon

* fixes spacing between elements

* Remove duplicate .setContentsMargins()

* Align children of FormWidget to center

* Remove workaround for empty label's size

No longer needed after some spacing fixes

* Do not set a fixed height

This allows the dialog to shrink to reduce wasted space if needed (e.g.
in the "Email Confirmation" dialog).

* Change email emoji

* Move timer.start() call to init_timer()

---------

Co-authored-by: Fernando Lins <fernandolins@users.noreply.github.com>