[ACTV-277] Implement Step deck tour (#1251)
* Support a callback for qt_target

* Use target.window() if no parent_widget

* Pass step to shown_callback

And call it earlier to allow mutations. This is required for the Deck
Options screen.

* Handle DeckOptionsDialog context

* Implement prompt for Step deck tour

* Wait for target element for a few seconds

Required for Svelte pages such as the Deck Options page.

* Allow toggling backdrop per step

* Add an option to remove parent's backdrop

* Only clean up previous step's webviews if not reused

* Pass given parent to _show_upsell

* Set object name for Flashcard Selector button

To make it easier to query

* Use primary color for target outline

* Add QtTutorialStep

- Separate Qt-specific args into a separate dataclass
- Make target optional
- Use target.window() or aqt.mw if parent_widget is not set
- Make target outline optional
- Add OverlayTarget that wraps a QWidget or QRect as a target

* Make extra_backdrop_contexts a method for consistency

* Add Tutorial.is_active

* Implement StepDeckTutorial

* Add tour triggers

* Remove unused Tutorial.name

* Add an option to restart tour at last step

* Set web app submodule to dev branch

* Add an option to hide step's close button

* Hide back button

* Move to next step if Deck Options opened manually

* Ensure deck is selected before starting tour

This ensures the gears icon is shown without having to hover

* Fix backdrop webviews not being cleaned up on exit

* Add note about Next button to Daily Limits step

* Handle unexpected Deck Options close

* Ensure we start browser with Cards mode

* Handle Browse button

* Go back to previous step if browser closed

* Show Deck Options / Browser window maximized

* Fix sidebar outline off by a few pixels

* Ensure tutorial is active before back/next/go_to_step calls

If the user closes the tour in the browser, the go_to_step() call at
browser shutdown was rendering the tour again.

* Rework browser hooking

If the browser opened multiple times during the tour, multiple on_browser_startup calls were being issued.
This was fixed by only registering our hooks once for the whole tour.

Also added wrap_method() and DebouncedDelayedCall helpers to improve
readability.

* Rename private methods

* Add generated tests

* Fix mypy errors

* Fix inverted feature flag check

* Remove some tests

Looks verbose and unnecessary

* Do not show prompt if deck is not installed

* Fix error on _deck_tree call

Was triggering this error:
```
TypeError: SidebarTreeView._deck_tree() got multiple values for argument 'self'
```

* Revert ankihub_web submodule to main branch

* Use logger

* Add product tours submenu

* Mention tour in congrats screen

* Add a tour link to instructions card

* Revert "Add a tour link to instructions card"

This reverts commit b0bfc9e598b038ab7451cda055b42519bf6dc665.

We decided to update the note instead. We'll need to update the link
when that's done in a similar way.